# Generated by Django 3.2.19 on 2023-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100, null='True')),
                ('genre', models.CharField(max_length=100, null='True')),
                ('year_of_publication', models.CharField(max_length=4, null='True')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
