# Generated by Django 3.2.19 on 2023-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookHandler', '0002_bookborrowdetails_bookstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrowdetails',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
