# Generated by Django 3.2.19 on 2023-05-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection', to='userHandler.student')),
                ('requested_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connections', to='userHandler.student')),
            ],
        ),
    ]
